### ISSUE TITLE
include-kirki.php

### ISSUE THREAD

**Issue by Rayken** [aristath/kirki-helpers#16] opened 2016-12-13 15:36 UTC
So I really can't get this to work anymore. I'm running WP v4.7 and the section just won't appear. I've tried adding a section manually with a setting, section and control and that works. It's as if it won't print because ```render()``` isn't triggered? I get no bugs with WP_DEBUG either, I just don't get it.

**Comment by aristath** [comment] 2016-12-13 15:41
Did you update to the new implementation?

**Comment by Rayken** [comment] 2016-12-13 15:46
@aristath I did, indeed. However I see now there's an inline "display: none;" being added from nowhere. I thought it was an PHP issue but it seems like WP doesn't like the section so it hides it? I don't know but it's being rendered although being hidden for some reason that's beyond me. Any idea?

So `<div style="padding:10px 14px;">` becomes `<div style="padding:10px 14px;display:none;">`

**Comment by ghost** [comment] 2016-12-19 00:53
I have the same issue trying to add a custom section. No matter what sort of combination of elements or class names, etc I use it adds display:none to it. I used the example to add the Typography section and it shows up and the styles appear to change in the customizer but not when viewing the live site like normal outside the customizer. Not sure if they are related or what I'm doing wrong.

**Comment by aristath** [comment] 2016-12-19 01:24
I'm not sure I understand the issue...

Are you referring to the CSS added on the frontend when Kirki is not installed?
Or are you referring to the custom section that's added to suggest users should install Kirki from the customizer?

**Comment by ghost** [comment] 2016-12-19 02:32
Sorry for the confusion. I was in a bit of a hurry so maybe I didn't explain it right.

First, I am having the exact same issue where the custom section added to suggest users install Kirki from the customizer doesn't show and has display:none on the section. I tried numerous combinations of elements in various orders and so forth. Maybe there's something to initialize the section so WP recognizes it should be there or something, I don't know.

Second, I thought that might somehow be related to another issue I'm having where the CSS isn't showing on the frontend for the Typography section that gets added which does show up because it does work in the cusotmizer but not on the frontend. I used the example from here: https://github.com/aristath/_s/blob/master/inc/customizer.php

Maybe it's a completely separate issue but since they are both related to CSS I just thought I should mention it.

Edit: To be clearer the CSS doesn't get added to the frontend when Kirki is or isn't installed. However even if I deactivate the Kirki plugin it does still appear to style the typography while in the customizer, just not the frontend. Also if this is a completely separate issue just say the word and I can make a new ticket no probs.

Edit2: So sorry for the edits and confusion. The second issue was an error on my part (I accidentally put the code to create the typography fields in the customize_register action instead of just on it's own) and seems to be unrelated as the first issue remains. So maybe just pretend my first post just says, "I also have this exact same issue, has anyone managed to find a fix yet?" =)

**Comment by Rayken** [comment] 2016-12-19 09:35
So we're back to the custom section that won't appear. Yes @aristath - it's the one that suggest users install/activate Kirki from the customizer. WordPress hides this custom section and my best bet is that it's because it can't find any controller or setting for this section so it remains hidden. This wasn't the case <4.7 but seems to be now? It's the only thing I can think of really.

**Comment by Rayken** [comment] 2016-12-19 11:25
Okay, apparently in order for a section to be shown you need to have a controller attached to it. As it appears, a controller has to have a setting for it to show which inadvertently seems to mean that for the section to show there has to be a controller that has a setting. The following fixes this as well as some minor styling "fixes". I don't know how to add a commit thing so I'll just post it here for you @aristath 


```PHP
<?php
/**
 * This file implements custom requirements for the Kirki plugin.
 * It can be used as-is in themes (drop-in).
 *
 * @package kirki-helpers
 */

if ( ! class_exists( 'Kirki' ) ) {

    if ( class_exists( 'WP_Customize_Section' ) && ! class_exists( 'Kirki_Installer_Section' ) ) {
        /**
         * Recommend the installation of Kirki using a custom section.
         *
         * @see WP_Customize_Section
         */
        class Kirki_Installer_Section extends WP_Customize_Section {

            /**
             * Customize section type.
             *
             * @access public
             * @var string
             */
            public $type = 'kirki_installer';

            /**
             * Render the section.
             *
             * @access protected
             */
            protected function render() {
                // Determine if the plugin is not installed, or just inactive.
                $plugins   = get_plugins();
                $installed = false;
                foreach ( $plugins as $plugin ) {
                    if ( 'Kirki' === $plugin['Name'] || 'Kirki Toolkit' === $plugin['Name'] ) {
                        $installed = true;
                    }
                }
                // Get the plugin-installation URL.
                $plugin_install_url = add_query_arg(
                    array(
                        'action' => 'install-plugin',
                        'plugin' => 'kirki',
                    ),
                    self_admin_url( 'update.php' )
                );
                $plugin_install_url = wp_nonce_url( $plugin_install_url, 'install-plugin_kirki' );
                $classes = 'cannot-expand accordion-section control-section control-section-themes control-section-' . $this->type;
                ?>
                <li id="accordion-section-<?php echo esc_attr( $this->id ); ?>" class="<?php echo esc_attr( $classes ); ?>" style="border-top:none;border-bottom:1px solid #ddd;padding:7px 14px 16px 14px;text-align:right;">
                    <?php if ( ! $installed ) : ?>
                        <p style="text-align:left;margin-top:0;"><?php esc_attr_e( 'A plugin is required to take advantage of this theme\'s features in the customizer.', 'textdomain' ); ?></p>
                        <a class="install-now button-primary button" data-slug="kirki" href="<?php echo esc_url_raw( $plugin_install_url ); ?>" aria-label="Install Kirki Toolkit now" data-name="Kirki Toolkit">
                            <?php esc_html_e( 'Install Now', 'textdomain' ); ?>
                        </a>
                    <?php else : ?>
                        <p style="text-align:left;margin-top:0;"><?php esc_attr_e( 'You have installed Kirki. Activate it to take advantage of this theme\'s features in the customizer.', 'textdomain' ); ?></p>
                        <a class="install-now button-secondary button change-theme" data-slug="kirki" href="<?php echo esc_url_raw( self_admin_url( 'plugins.php' ) ); ?>" aria-label="Activate Kirki Toolkit now" data-name="Kirki Toolkit">
                            <?php esc_html_e( 'Activate Now', 'textdomain' ); ?>
                        </a>
                    <?php endif; ?>
                </li>
                <?php
            }
        }
    }

    if ( ! function_exists( 'kirki_installer_register' ) ) {
        /**
         * Registers the section, setting & control for the kirki installer.
         *
         * @param object $wp_customize The main customizer object.
         */
        function kirki_installer_register( $wp_customize ) {
            $wp_customize->add_section( new Kirki_Installer_Section( $wp_customize, 'kirki_installer', array(
                'title'      => '',
                'capability' => 'install_plugins',
                'priority'   => 0,
            ) ) );
            
            $wp_customize->add_setting( 'kirki_installer_setting', array() );
                 
            $wp_customize->add_control( 'kirki_installer_control', array(
                'section'    => 'kirki_installer',
                'settings'   => 'kirki_installer_setting',
            ) );

        }
        add_action( 'customize_register', 'kirki_installer_register' );
    }
}
```

**Comment by aristath** [comment] 2016-12-19 20:00
@Quaked you're absolutely right, pushed a commit with those.

**Comment by aristath** [comment] 2016-12-19 20:10
@ty2u the section is now properly added (I pushed some code provided by @Quaked and that fixed it). Reading your comments above I'm assuming that means we can now close this issue, right? The CSS on the frontend issue appears to be a non-issue from what I understood 😄

**Comment by Rayken** [comment] 2016-12-19 20:20
All right! Oh, if there's one thing I'd suggest you keep from the code I
provided, if not the fixes for styling, it would be the use of <li> rather
than <div> as it's not "valid" for a div to be the direct child of <ul>.
You could put the div inside an <li> though!

The styling fixes mainly move a misplaced border and has accurate padding
as well as some spacing for the button (aligned right).

**Comment by ghost** [comment] 2016-12-19 21:18
I can confirm that this fix works! The section is now visible. Awesome stuff!

**Comment by aristath** [comment] 2016-12-19 21:20
@Quaked huh... tbh I completely missed those changes earlier, I only saw the setting & control additions.
Very well, added those too. 👍

**Closed as completed by aristath** 2016-12-19 21:20 UTC
Labels: bug
